// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPeA7uCHGe3EEOkZiJoqaPTh-cNepfWIE',
    appId: '1:830804675662:web:1577672972f3c4d705471f',
    messagingSenderId: '830804675662',
    projectId: 'techgen-android-ios-firebase',
    authDomain: 'techgen-android-ios-firebase.firebaseapp.com',
    storageBucket: 'techgen-android-ios-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVyp3B-UF_LuPoHJ11RFVf2yWM9HFv3jk',
    appId: '1:830804675662:android:7637bddac96b413405471f',
    messagingSenderId: '830804675662',
    projectId: 'techgen-android-ios-firebase',
    storageBucket: 'techgen-android-ios-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYVYASL3j8kFctYIUlbbzpyKHhttiFfE',
    appId: '1:830804675662:ios:66232613a39de30b05471f',
    messagingSenderId: '830804675662',
    projectId: 'techgen-android-ios-firebase',
    storageBucket: 'techgen-android-ios-firebase.appspot.com',
    iosClientId: '830804675662-9345f8vdapfrs7np9ria6mff10fa7u9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.techgen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYVYASL3j8kFctYIUlbbzpyKHhttiFfE',
    appId: '1:830804675662:ios:66232613a39de30b05471f',
    messagingSenderId: '830804675662',
    projectId: 'techgen-android-ios-firebase',
    storageBucket: 'techgen-android-ios-firebase.appspot.com',
    iosClientId: '830804675662-9345f8vdapfrs7np9ria6mff10fa7u9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.techgen',
  );
}
